language: go
go_import_path: github.com/m-zajac/goprojectdemo
go:
  - 1.11.x

script:
  - env GO111MODULE=on go build ./cmd/...
  - env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
