// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Request struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	ProjectsCount        int32    `protobuf:"varint,2,opt,name=projectsCount,proto3" json:"projectsCount,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4a588c488e60730f, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Request) GetProjectsCount() int32 {
	if m != nil {
		return m.ProjectsCount
	}
	return 0
}

func (m *Request) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// The response message containing the greetings
type Reply struct {
	Stat                 []*Stat  `protobuf:"bytes,1,rep,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4a588c488e60730f, []int{1}
}
func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (dst *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(dst, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetStat() []*Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type Stat struct {
	Contributor          *Contributor `protobuf:"bytes,1,opt,name=contributor,proto3" json:"contributor,omitempty"`
	Commits              int32        `protobuf:"varint,2,opt,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Stat) Reset()         { *m = Stat{} }
func (m *Stat) String() string { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()    {}
func (*Stat) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4a588c488e60730f, []int{2}
}
func (m *Stat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stat.Unmarshal(m, b)
}
func (m *Stat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stat.Marshal(b, m, deterministic)
}
func (dst *Stat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stat.Merge(dst, src)
}
func (m *Stat) XXX_Size() int {
	return xxx_messageInfo_Stat.Size(m)
}
func (m *Stat) XXX_DiscardUnknown() {
	xxx_messageInfo_Stat.DiscardUnknown(m)
}

var xxx_messageInfo_Stat proto.InternalMessageInfo

func (m *Stat) GetContributor() *Contributor {
	if m != nil {
		return m.Contributor
	}
	return nil
}

func (m *Stat) GetCommits() int32 {
	if m != nil {
		return m.Commits
	}
	return 0
}

type Contributor struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contributor) Reset()         { *m = Contributor{} }
func (m *Contributor) String() string { return proto.CompactTextString(m) }
func (*Contributor) ProtoMessage()    {}
func (*Contributor) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_4a588c488e60730f, []int{3}
}
func (m *Contributor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contributor.Unmarshal(m, b)
}
func (m *Contributor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contributor.Marshal(b, m, deterministic)
}
func (dst *Contributor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contributor.Merge(dst, src)
}
func (m *Contributor) XXX_Size() int {
	return xxx_messageInfo_Contributor.Size(m)
}
func (m *Contributor) XXX_DiscardUnknown() {
	xxx_messageInfo_Contributor.DiscardUnknown(m)
}

var xxx_messageInfo_Contributor proto.InternalMessageInfo

func (m *Contributor) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contributor) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterType((*Reply)(nil), "grpc.Reply")
	proto.RegisterType((*Stat)(nil), "grpc.Stat")
	proto.RegisterType((*Contributor)(nil), "grpc.Contributor")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	// Return most active contributors
	MostActiveContributors(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) MostActiveContributors(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/grpc.Service/MostActiveContributors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	// Return most active contributors
	MostActiveContributors(context.Context, *Request) (*Reply, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_MostActiveContributors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).MostActiveContributors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Service/MostActiveContributors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).MostActiveContributors(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MostActiveContributors",
			Handler:    _Service_MostActiveContributors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_4a588c488e60730f) }

var fileDescriptor_service_4a588c488e60730f = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4d, 0x6b, 0x83, 0x40,
	0x10, 0x86, 0xeb, 0x57, 0x6d, 0x46, 0x2c, 0x74, 0x28, 0x45, 0x72, 0x28, 0x22, 0x85, 0x7a, 0xf2,
	0xa0, 0xd0, 0x7b, 0xc8, 0xb9, 0x97, 0x0d, 0xfd, 0x01, 0x66, 0xb3, 0xc8, 0x16, 0xe3, 0xda, 0xdd,
	0x31, 0x90, 0x7f, 0x5f, 0xdc, 0x4d, 0x5a, 0x73, 0x7c, 0xe6, 0x9d, 0x19, 0x1e, 0x5e, 0x48, 0x8d,
	0xd0, 0x27, 0xc9, 0x45, 0x35, 0x6a, 0x45, 0x0a, 0xc3, 0x4e, 0x8f, 0xbc, 0x68, 0x21, 0x66, 0xe2,
	0x67, 0x12, 0x86, 0x70, 0x0d, 0x0f, 0x7d, 0x3b, 0x74, 0x53, 0xdb, 0x89, 0xcc, 0xcb, 0xbd, 0x72,
	0xc5, 0xfe, 0x18, 0xdf, 0x20, 0x1d, 0xb5, 0xfa, 0x16, 0x9c, 0xcc, 0x56, 0x4d, 0x03, 0x65, 0x7e,
	0xee, 0x95, 0x11, 0xbb, 0x1d, 0xe2, 0x33, 0x44, 0xdc, 0xa6, 0x81, 0x4d, 0x1d, 0x14, 0xef, 0x10,
	0x31, 0x31, 0xf6, 0x67, 0x7c, 0x85, 0xd0, 0x50, 0x4b, 0x99, 0x97, 0x07, 0x65, 0x52, 0x43, 0x35,
	0x0b, 0x54, 0x3b, 0x6a, 0x89, 0xd9, 0x79, 0xf1, 0x05, 0xe1, 0x4c, 0xd8, 0x40, 0xc2, 0xd5, 0x40,
	0x5a, 0xee, 0x27, 0x52, 0xda, 0xba, 0x24, 0xf5, 0x93, 0x5b, 0xdf, 0xfe, 0x07, 0x6c, 0xb9, 0x85,
	0x19, 0xc4, 0x5c, 0x1d, 0x8f, 0x92, 0xcc, 0xc5, 0xed, 0x8a, 0x45, 0x03, 0xc9, 0xe2, 0x0a, 0x1f,
	0xc1, 0x97, 0x07, 0xfb, 0x34, 0x60, 0xbe, 0x3c, 0xcc, 0xd2, 0xbd, 0xea, 0xe4, 0x60, 0xcf, 0x56,
	0xcc, 0x41, 0xbd, 0x81, 0x78, 0xe7, 0xea, 0xc2, 0x0f, 0x78, 0xf9, 0x54, 0x86, 0x36, 0x9c, 0xe4,
	0x49, 0x2c, 0x3e, 0x19, 0x4c, 0x9d, 0xd3, 0xa5, 0xc0, 0x75, 0x72, 0xc5, 0xb1, 0x3f, 0x17, 0x77,
	0xfb, 0x7b, 0xdb, 0x73, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xce, 0xf3, 0x26, 0x00, 0x78, 0x01,
	0x00, 0x00,
}
