// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m-zajac/goprojectdemo/internal/api/http (interfaces: Service)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	app "github.com/m-zajac/goprojectdemo/internal/app"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// MostActiveContributors mocks base method
func (m *MockService) MostActiveContributors(arg0 context.Context, arg1 string, arg2, arg3 int) ([]app.ContributorStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MostActiveContributors", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]app.ContributorStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MostActiveContributors indicates an expected call of MostActiveContributors
func (mr *MockServiceMockRecorder) MostActiveContributors(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MostActiveContributors", reflect.TypeOf((*MockService)(nil).MostActiveContributors), arg0, arg1, arg2, arg3)
}
